### PR TITLE
Add wrapper for eigenvalues and eigenvector of symmetric matrix

### PR DESCRIPTION
**Pull request by keyehzy**
Hello there :wave: . 

I'm using the following code for my personal usage so I figured I make a PR for it, so other users benefit from it. This is PR for a wrapper of the ?syevr LAPACK function, computing eigvenvalues and eigenvectors of a symmetric real matrix. I notice that there is already a function to compute eigenvalues for a general matrix but there are a few problems. 1) Eigenvectors are not computed 2) Not a particular efficient for symmetric matrices. 

Let me know if you like this.

### CODE REVIEW

**Comment by andreaferretti** [comment]
Hi @keyehzy, thank you very much for your contribution! From skimming the code, it looks fine to me, but when I try it, your own tests do not pass:

```
[Suite] computing eigenvalues and eigenvectors of real symmetric matrix
@[@[0.02973201918098609, -0.7774829502258251, 0.5975418503203069, 0.1938556325190275], @[-0.6961670446233255, -0.01564107199963255, -0.2085096947417681, 0.6867536021353086], @[0.5433962232843438, -0.3973078598942641, -0.655220563815919, 0.3428600614526292], @[-0.4681751782571962, -0.4872597699801298, -0.4124966146130511, -0.6109308160139947]]
    /Users/andrea/progetti/neo/tests/dense/deigenvalues.nim(105, 59): Check failed: abs(vecs.real[i][j] - expected_vecs[i][j]) < 0.0000001
    abs(vecs.real[i][j] - expected_vecs[i][j]) was 0.9363503552161462
    /Users/andrea/progetti/neo/tests/dense/deigenvalues.nim(105, 59): Check failed: abs(vecs.real[i][j] - expected_vecs[i][j]) < 0.0000001
    abs(vecs.real[i][j] - expected_vecs[i][j]) was 0.9745195399707188
    /Users/andrea/progetti/neo/tests/dense/deigenvalues.nim(105, 59): Check failed: abs(vecs.real[i][j] - expected_vecs[i][j]) < 0.0000001
    abs(vecs.real[i][j] - expected_vecs[i][j]) was 0.8249932304435421
    /Users/andrea/progetti/neo/tests/dense/deigenvalues.nim(105, 59): Check failed: abs(vecs.real[i][j] - expected_vecs[i][j]) < 0.0000001
    abs(vecs.real[i][j] - expected_vecs[i][j]) was 1.221861632192526
  [FAILED] computing the eigenvalues
```

I assume that they *do* pass on your system. Can I ask you where are you running them?

**Comment by keyehzy** [comment]
It seems that implementations of LAPACK might compute eigenvectors with a minus sign difference. If we compare our results

```diff
--- /tmp/ediffh5lUI9	2022-02-17 13:28:02.860378460 -0300
+++ /tmp/ediff9Gkf6w	2022-02-17 13:28:02.860378460 -0300
@@ -1,4 +1,4 @@
-@[@[0.02973201918098634, -0.7774829502258251, 0.5975418503203074, 0.1938556325190272],
-  @[-0.6961670446233259, -0.01564107199963272, -0.2085096947417675, 0.6867536021353086],
-  @[0.5433962232843441, -0.3973078598942644, -0.6552205638159185, 0.342860061452629],
-  @[0.4681751782571961, 0.48725976998013, 0.4124966146130512, 0.6109308160139947]]
\ No newline at end of file
+@[@[0.02973201918098609, -0.7774829502258251, 0.5975418503203069, 0.1938556325190275],
+  @[-0.6961670446233255, -0.01564107199963255, -0.2085096947417681, 0.6867536021353086],
+  @[0.5433962232843438, -0.3973078598942641, -0.655220563815919, 0.3428600614526292],
+  @[-0.4681751782571962, -0.4872597699801298, -0.4124966146130511, -0.6109308160139947]]
\ No newline at end of file
```

Other than differences in the last decimal places, the last eigenvector has an overall minus sign difference. As I understand, both answers are correct but I'm not sure show to address this in testing.

**Comment by andreaferretti** [comment]
I had not noticed that there were just swapped signs. This should be easy to fix in the tests: for each vector v, compute the dot product with the expected vector; if this is negative, swap the signs of v. Then, run tests as before

**Comment by keyehzy** [comment]
I adapted the tests to use vectors instead of seq's.

**Comment by andreaferretti** [comment]
Thank you, I have merged and bumped version to 0.3.2!

**Pull request merged**
