### PR TITLE
Shortcut determinant for 2x2 matrix

### PR DESCRIPTION
**Pull request by modoodalvi**
Fixing #51

### CODE REVIEW

**Comment by andreaferretti** [comment]
Thank you, but it seems that this just fixes the 2x2 case, and it is not clear to me that other dimensions are not buggy as well. Do you have an idea why t he schur factorization fails for this 2x2 matrix?

**Comment by modoodalvi** [comment]
I don't know. I didn't check.

**Comment by modoodalvi** [comment]
@andreaferretti What chances do we have to get #51 fixed any time soon?

**Comment by andreaferretti** [comment]
As soon as someone finds the root cause and proposes a fix that will work with any size, I will accept it. I am not planning of special casing 2x2 matrices for two reasons:
* it is trivial to write the formula on one's own
* the size is so small that we don't need to rely on decompositions

If I did that, chances are the real bug will not be found. I will leave this open until the actual reason for failure is clear

**Pull request closed without merging**
